create table if not exists public.daily_moods (
  id bigint generated by default as identity primary key,
  player text not null check (player in ('Thorsten', 'Basti', 'Marian', 'Fabi')),
  mood_date date not null,
  mood_value smallint not null check (mood_value between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player, mood_date)
);

alter table public.daily_moods enable row level security;

drop policy if exists "Daily moods public read" on public.daily_moods;
create policy "Daily moods public read" on public.daily_moods
  for select to anon using (true);

drop policy if exists "Daily moods public insert" on public.daily_moods;
create policy "Daily moods public insert" on public.daily_moods
  for insert to anon with check (
    player in ('Thorsten', 'Basti', 'Marian', 'Fabi')
    and mood_value between 1 and 5
  );

drop policy if exists "Daily moods public update" on public.daily_moods;
create policy "Daily moods public update" on public.daily_moods
  for update to anon using (true) with check (
    player in ('Thorsten', 'Basti', 'Marian', 'Fabi')
    and mood_value between 1 and 5
  );

drop policy if exists "Daily moods public delete" on public.daily_moods;
create policy "Daily moods public delete" on public.daily_moods
  for delete to anon using (true);

create index if not exists daily_moods_player_date_idx
  on public.daily_moods (player, mood_date desc);
