create table if not exists public.dart_throws (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.dart_games(id) on delete cascade,
  player text not null,
  turn_number integer not null check (turn_number > 0),
  dart_position smallint not null check (dart_position between 1 and 3),
  base_value smallint not null check (base_value between 0 and 25),
  multiplier smallint not null check (multiplier between 1 and 3),
  scored_value smallint not null check (scored_value between 0 and 60),
  is_miss boolean not null default false,
  is_bust boolean not null default false,
  created_at timestamptz not null default now(),
  constraint dart_throws_valid_bull check (base_value <> 25 or multiplier <= 2),
  constraint dart_throws_valid_miss check (not is_miss or scored_value = 0)
);

alter table public.dart_throws enable row level security;

drop policy if exists "Dart throws public read" on public.dart_throws;
create policy "Dart throws public read" on public.dart_throws
  for select to anon using (true);

drop policy if exists "Dart throws public insert" on public.dart_throws;
create policy "Dart throws public insert" on public.dart_throws
  for insert to anon with check (
    char_length(btrim(player)) between 1 and 80
    and turn_number > 0
    and dart_position between 1 and 3
    and base_value between 0 and 25
    and multiplier between 1 and 3
    and scored_value between 0 and 60
  );

create index if not exists dart_throws_game_idx on public.dart_throws (game_id);
create index if not exists dart_throws_player_idx on public.dart_throws (player);
create index if not exists dart_throws_segment_idx on public.dart_throws (base_value, multiplier);
