create table if not exists public.game_collection_rounds (
  id bigint generated by default as identity primary key,
  game_name text not null,
  game_date date not null default current_date,
  results jsonb not null,
  created_at timestamptz not null default now(),
  constraint game_collection_name_length
    check (char_length(btrim(game_name)) between 1 and 80),
  constraint game_collection_results_array
    check (jsonb_typeof(results) = 'array' and jsonb_array_length(results) between 2 and 20)
);

alter table public.game_collection_rounds enable row level security;

drop policy if exists "Game collection public read"
  on public.game_collection_rounds;
create policy "Game collection public read"
  on public.game_collection_rounds
  for select
  to anon
  using (true);

drop policy if exists "Game collection public insert"
  on public.game_collection_rounds;
create policy "Game collection public insert"
  on public.game_collection_rounds
  for insert
  to anon
  with check (
    char_length(btrim(game_name)) between 1 and 80
    and jsonb_typeof(results) = 'array'
    and jsonb_array_length(results) between 2 and 20
  );

drop policy if exists "Game collection public delete"
  on public.game_collection_rounds;
create policy "Game collection public delete"
  on public.game_collection_rounds
  for delete
  to anon
  using (true);

create index if not exists game_collection_rounds_date_idx
  on public.game_collection_rounds (game_date desc, created_at desc);

create index if not exists game_collection_rounds_name_idx
  on public.game_collection_rounds (game_name);
