const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'); const read=p=>fs.readFileSync(path.join(root,p),'utf8');
function context(date, storage=new Map(), hostname='localhost', backend=null){
 const location=new URL(`http://${hostname}/?holiday=${date}&holiday-player=Thorsten`);
 const c={URL,URLSearchParams,console,location,Date:class extends Date{constructor(...a){super(...(a.length?a:[date+'T12:00:00']));}},history:{state:null,replaceState(_s,_t,url){location.href=url.href;}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},supabaseClient:backend||{from(){throw Error('Preview contacted database');},rpc(){throw Error('Preview wrote database');}}};
 c.window=c;vm.createContext(c);for(const f of ['scoring.js','modules/holidays/holiday-calendar.js','modules/birthday/member-birthday-data.js','modules/holidays/holiday-data.js'])vm.runInContext(read(f),c);return c;
}
function extract(name){const html=read('index.html'),start=html.indexOf('    function '+name+'(');assert.ok(start>=0);return html.slice(start,html.indexOf('\n    function ',start+10));}
(async()=>{
 const c=context('2026-04-05'), C=c.WRCHolidayCalendar;
 for(const [date,type] of Object.entries({'2026-04-04':null,'2026-04-05':'easter','2026-04-06':'easter','2026-04-07':null,'2026-10-30':null,'2026-10-31':'halloween','2026-11-01':null,'2026-12-05':null,'2026-12-06':'nikolaus','2026-12-07':null,'2026-12-23':null,'2026-12-24':'christmas','2026-12-25':'christmas','2026-12-26':'christmas','2026-12-27':null,'2026-12-30':null,'2026-12-31':'newyear','2027-01-01':null}))assert.equal(C.resolve(date)?.type||null,type,date);
 assert.equal(C.easter(2027),'2027-03-28');assert.equal(C.easter(2028),'2028-04-16');assert.equal(C.resolve('2026-02-30'),null);
 for(let y=2026;y<2040;y++){assert.equal(new Set([0,1,2,3].map(s=>C.eggOwner(y,s))).size,4);for(let s=0;s<4;s++)assert.notEqual(C.eggOwner(y,s),C.eggOwner(y+1,s));}
 const storage=new Map(); let e=context('2026-04-05',storage);await e.WRCBonusPoints.load();
 for(let slot=0;slot<4;slot++){const owner=C.eggOwner(2026,slot),wrong=C.members.find(p=>p!==owner);await assert.rejects(e.WRCHolidayData.claim('easter',wrong,{slot}));await e.WRCHolidayData.claim('easter',owner,{slot});await e.WRCHolidayData.claim('easter',owner,{slot});assert.equal(e.WRCBonusPoints.points({person:owner}),5);}
 assert.equal(context('2026-04-06',storage).WRCBonusPoints.points(),20);await assert.rejects(context('2026-04-07',storage).WRCHolidayData.claim('easter','Thorsten',{slot:2}));assert.equal(context('2026-04-07',storage).WRCBonusPoints.points(),20);
 for(const date of ['2026-12-24','2026-12-25','2026-12-26']){const x=context(date,storage);for(const p of C.members)await x.WRCHolidayData.claim('christmas',p);assert.equal(x.WRCBonusPoints.points({key:'2026-12'}),20);}
 assert.equal(context('2026-12-27',storage).WRCBonusPoints.points(),40);await assert.rejects(context('2026-12-27',storage).WRCHolidayData.claim('christmas','Fabi'));
 for(const [date,type] of [['2026-10-31','halloween'],['2026-12-06','nikolaus'],['2026-12-31','newyear']]){const x=context(date,storage);for(const p of C.members){const r=await x.WRCHolidayData.claim(type,p,{choice:type==='halloween'?1:undefined});const again=await context(date,storage).WRCHolidayData.claim(type,p,{choice:type==='halloween'?0:undefined});assert.equal(r.points,0);assert.equal(r.result,again.result);}assert.equal(x.WRCBonusPoints.points(),40);}
 // Production ignores preview query strings; independent devices share server receipts.
 const shared=new Map();let rpcCalls=0;const backend={from(){return{select(){return this},order(){return this},range:async()=>({data:[...shared.values()],error:null})}},async rpc(name,a){rpcCalls++;assert.equal(name,'claim_wrc_holiday');assert.deepEqual(Object.keys(a).sort(),['p_choice','p_egg_slot','p_event','p_player']);const key=a.p_event+':'+a.p_player;if(!shared.has(key))shared.set(key,{event_type:a.p_event,event_year:2026,player:a.p_player,event_date:'2026-12-24',points:5,choice:null,result:null});return{data:[shared.get(key)],error:null};}};
 const a=context('2026-12-24',new Map(),'example.com',backend),b=context('2026-12-24',new Map(),'example.com',backend);assert.equal(a.WRCHolidayData.preview,false);assert.equal(a.WRCBirthdayData.preview,false);await Promise.all([a.WRCHolidayData.load(),b.WRCHolidayData.load()]);await Promise.all([a.WRCHolidayData.claim('christmas','Fabi'),b.WRCHolidayData.claim('christmas','Fabi')]);assert.equal(shared.size,1);assert.equal(rpcCalls,2);await b.WRCHolidayData.load();assert.equal(b.WRCBonusPoints.points(),5);
 // Real central forecast: bonuses count exactly once, never in fitness pace.
 for(const [date,type,slot] of [['2026-04-05','easter',2],['2026-12-24','christmas',undefined]]){
  const x=context(date),key=date.slice(0,7);x.people=Array.from(C.members);x.allEntries=[];for(let day=1;day<=3;day++)for(const person of x.people)x.allEntries.push({person,date:`${key}-0${day}`,steps:10000});x.monthGoals={[key]:1000};x.HISTORIC_MONTH_POINTS={};
  for(const n of ['monthTotalPoints','getTeamMonthForecast'])vm.runInContext(extract(n),x);
  const before=x.getTeamMonthForecast(key),snapshot=JSON.stringify(x.allEntries);await x.WRCHolidayData.claim(type,'Thorsten',{slot});const after=x.getTeamMonthForecast(key);
  assert.equal(after.currentTotal-before.currentTotal,5);assert.equal(after.forecast-before.forecast,5);assert.equal(after.basisTotal,before.basisTotal);assert.equal(after.basisDate,before.basisDate);assert.equal(x.monthTotalPoints(key),after.currentTotal);assert.equal(JSON.stringify(x.allEntries),snapshot);
 }
 const x=context('2026-12-31',storage),entries=[{person:'Thorsten',date:'2026-05-01',steps:10000,bike:5},{person:'Fabi',date:'2026-05-01',steps:5000},{person:'Guest',date:'2026-05-01',steps:1000000},{person:'Thorsten',date:'2027-01-01',steps:1000000}];const snapshot=JSON.stringify(entries),stats=x.WRCHolidayData.yearStats(entries,2026,'Thorsten','2026-12-31',{points:100,steps:1000,bike:2},()=>[]);assert.equal(stats.steps,11000);assert.equal(stats.bike,7);assert.equal(stats.bonus,10);assert.equal(stats.days,1);assert.equal(JSON.stringify(entries),snapshot);assert.equal(x.WRCHolidayData.yearStats([],2027,null,'2027-12-31',{points:100},()=>[]).points,0);
 // Every new cached file exists; all authored JS and inline app scripts parse.
 const sw=read('service-worker.js');for(const m of sw.matchAll(/"\.\/([^"?#]+)"/g))assert.ok(fs.existsSync(path.join(root,m[1])),m[1]);
 for(const f of ['holiday-calendar.js','holiday-data.js','holidays.js'])new vm.Script(read('modules/holidays/'+f));for(const m of read('index.html').matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!m[1].includes('src=')&&m[2].trim())new vm.Script(m[2]);
 console.log('PASS: all holiday boundaries, Easter mapping/all players/wrong eggs, exact +5, reload/expiry, saved Halloween/zero awards, production preview guard, two-device race, real forecast/fitness invariance, annual stats, PWA assets and syntax.');
})().catch(e=>{console.error(e);process.exitCode=1;});
